spring:
  application:
    name: kata-sg-iam-crud
  datasource:
    url: jdbc:postgresql://localhost/kata_sgiam_database
    username: sgiam_user
    password: secure_password
  flyway:
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
server:
  ssl:
    key-store: classpath:sgiamkata.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: sgiamkata
    key-password: password
  port: 8443

management:
  security:
    enabled: false

  endpoints:
    web:
      base-path: /admin